//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arabia.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class League
    {
        public League()
        {
            this.Seasons = new HashSet<Season>();
        }
    
        public int LeagueId { get; set; }
        public Nullable<short> TypeId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string Name { get; set; }
        public string NameEn { get; set; }
        public string FullName { get; set; }
        public string Abbreviation { get; set; }
        public string LogoUrl { get; set; }
        public string Uripath { get; set; }
        public string ApiKey { get; set; }
        public Nullable<bool> HaveClubs { get; set; }
        public Nullable<bool> IsAuthorized { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual ICollection<Season> Seasons { get; set; }
    }
}
